# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f53b53e0664a9e12b1831129cdf912664f1a13cf8f788dde4c5bb241487641c5f31e965d185288405aa535adb6b84bf21d0ba6af732192fcf5922476b91373f8

test:
  secret_key_base: f328fd48934a37f34b466c2782594da89612d4e9219c1e5cdd57cf8453605674baf731f1d40d2d4787ffb2d2a9ce203f06ac31aba7009e79ffc4f9481e8b9b63

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
